import {
  faFolder,
  faCamera,
  faPalette,
  faFileAlt,
  faFont,
  faCube,
  faIcons,
  faImage,
  faTag,
  faShapes,
  faObjectGroup,
  faPaintBrush,
  faPencilRuler,
  faLayerGroup,
  faStar,
  faSearch,
  faFire,
  faVideo,
  faBriefcase,
  faGraduationCap,
  faBullhorn,
  faNewspaper,
  faHeart,
  faChartLine,
  faCrown,
  faWandMagicSparkles,
  faGift,
  faShop,
} from "@fortawesome/free-solid-svg-icons"

const ICON_MAP: Record<string, unknown> = {
  faFolder,
  faCamera,
  faPalette,
  faFileAlt,
  faFont,
  faCube,
  faIcons,
  faImage,
  faTag,
  faShapes,
  faObjectGroup,
  faPaintBrush,
  faPencilRuler,
  faLayerGroup,
  faStar,
  faSearch,
  faFire,
  faVideo,
  faBriefcase,
  faGraduationCap,
  faBullhorn,
  faNewspaper,
  faHeart,
  faChartLine,
  faCrown,
  faWandMagicSparkles,
  faGift,
  faShop,
}

export function getIconDefinition(iconName: string) {
  return (ICON_MAP[iconName] as ReturnType<typeof faFolder>) || faFolder
}

export const FA_ICON_MAP: Record<string, string> = {
  faFolder: "Folder",
  faCamera: "Camera",
  faPalette: "Palette",
  faFileAlt: "File",
  faFont: "Font",
  faCube: "3D Cube",
  faIcons: "Icons",
  faImage: "Image",
  faTag: "Tag",
  faShapes: "Shapes",
  faObjectGroup: "Vector",
  faPaintBrush: "Paint Brush",
  faPencilRuler: "Pencil Ruler",
  faLayerGroup: "Layers",
  faStar: "Star",
  faSearch: "Search",
  faFire: "Fire/Trending",
  faVideo: "Video/YouTube",
  faBriefcase: "Resume/Business",
  faGraduationCap: "Education",
  faBullhorn: "Social Media",
  faNewspaper: "Blog/Article",
  faHeart: "Lifestyle",
  faChartLine: "Analytics",
  faCrown: "Premium",
  faWandMagicSparkles: "Creative",
  faGift: "Free/Bundle",
  faShop: "Shop/Store",
}

export const FA_ICON_OPTIONS = Object.keys(FA_ICON_MAP)
